name: TestDemo

on:
    workflow_dispatch:
        inputs:
            is_build:
                description: 'Do you want to build'
                required: true
                default: false

jobs:
    build:
        
        if: ${{ inputs.is_build }} == 'true'
        runs-on: demo-lab # use lab for self-hosted runner
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Compling Code
              run: echo "Compiling Code" 

            - name: Test Code
              run: echo "Test Code" 

            
